import { IsUuidLike } from '../../../common/validation/is-uuid-like';

/** register-candidate.dto.ts — DOM-040. `indexNumber` is generated by the
 * service from the student's own school code + academic year + a
 * sequence, never caller-supplied — see nacca.service.ts's
 * registerCandidate() for why (derived from real data, not trusted
 * client input, and can't drift out of sync with the school it names). */
export class RegisterCandidateDto {
  @IsUuidLike()
  studentId!: string;

  @IsUuidLike()
  academicYearId!: string;
}
